language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - node
branches:
  except:
    - experimental
before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
addons:
    chrome: stable